"""Serve the derived architecture map and its conformance report.

Both artifacts are generated by backend/scripts/extract_architecture.py and
check_architecture.py and committed to architecture/. They are read from disk
rather than computed per request: generation walks the repository source
inventory, and the map only changes when the code does.

Mounted under /admin because that prefix is already proxied by vite; see
frontend/vite.config.ts.
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from app.config import settings

router = APIRouter(prefix="/admin/architecture", tags=["architecture"])

# routers -> app -> backend -> repo root
_ARCH_DIR = (
    Path(settings.corvus_architecture_dir).expanduser().resolve()
    if settings.corvus_architecture_dir
    else Path(__file__).resolve().parents[3] / "architecture"
)


def _load(name: str) -> dict:
    path = _ARCH_DIR / name
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                f"{name} not generated. Run: python backend/scripts/"
                f"extract_architecture.py && backend/venv/bin/python "
                f"backend/scripts/check_architecture.py"
            ),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"{name} is not valid JSON: {exc}") from exc


@router.get("")
async def get_architecture() -> dict:
    """Boxes, drift, invariant verdicts, and the frontend/backend route join.

    Returns the conformance report plus the slices of the raw map the UI needs.
    The full map contains module-level detail the overview does not need, so
    this endpoint returns only the reviewed and UI-facing slices.
    """
    arch = _load("architecture.json")
    conf = _load("conformance.json")
    return {
        "schema_version": conf.get("schema_version"),
        "totals": {**arch["totals"], **conf["totals"]},
        "review": conf.get("review", {}),
        "system_summary": conf.get("system_summary", {}),
        "memory_engine": conf.get("memory_engine", {}),
        "system_context": conf.get("system_context", {}),
        "runtime_nodes": conf.get("runtime_nodes", []),
        "runtime_connections": conf.get("runtime_connections", []),
        "bounded_contexts": conf.get("bounded_contexts", []),
        "deployments": conf.get("deployments", []),
        "decisions": conf.get("decisions", []),
        "freshness": conf.get("freshness", {}),
        "processes": conf.get("processes", conf.get("paths", [])),
        "boxes": conf["boxes"],
        "unclassified": conf["unclassified"],
        "violations": conf["violations"],
        "unchecked_invariants": conf["unchecked_invariants"],
        "phantom_boxes": conf["phantom_boxes"],
        "manifest_problems": conf["manifest_problems"],
        "paths": conf["paths"],
        "import_cycles": arch.get("import_cycles", []),
        "route_join": arch.get("route_join", {}),
        "background_candidates": arch.get("background_candidates", []),
    }


@router.get("/module/{module_name}")
async def get_module(module_name: str) -> dict:
    """Detail for one module: imports, importers, routes, db writes, llm sites."""
    arch = _load("architecture.json")
    info = arch["modules"].get(module_name)
    if not info:
        raise HTTPException(status_code=404, detail=f"unknown module: {module_name}")
    return {**info, "imported_by": arch.get("imported_by", {}).get(module_name, [])}
