/* GENERATED by scripts/generate-contracts.mjs — do not edit.
 * Source: backend/tests/contracts/surface.*.json (corvus-locomo, corvus-mind).
 * Regenerate with `npm run gen:contracts`; CI fails on drift.
 *
 * Composition is per-tenant, so "the API" is not one surface. This table is
 * how the client tells an UNGRANTED route apart from a FAILED one.
 */

export type Capability =
  | 'evaluation'
  | 'external_api'
  | 'governance'
  | 'ingestion'
  | 'knowledge_graph'
  | 'memory'
  | 'operator'

export type TenantId =
  | 'corvus-locomo'
  | 'corvus-mind'

export interface RouteContract {
  readonly method: string
  readonly path: string
  readonly capability: Capability
  /** Tenants whose composed application mounts this route. */
  readonly tenants: readonly TenantId[]
}

/** Every capability-owned route documented by at least one tenant profile. */
export const ROUTE_CONTRACTS: readonly RouteContract[] = [
  { method: 'GET', path: '/admin/alerts', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/alerts/{alert_id}/acknowledge', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/alerts/acknowledge-all', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/architecture', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/architecture/module/{module_name}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/audit-log', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/audit-log/summary', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/bootstrap-firings', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/bootstrap-stats', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/checkpoint', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/classify-edges', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/compliance-audit', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/concept-neurons', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/concept-neurons', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/concept-neurons/{concept_id}/link', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/concept-neurons/relink', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/concept-neurons/seed-all', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/concept-neurons/seed-three-horizons', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/cost-report', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/documents/', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/documents/{job_id}', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/documents/{job_id}/cancel', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/documents/{job_id}/structure', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/documents/upload', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/embed-neurons', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/emergent-queue', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/emergent-queue/{entry_id}/dismiss', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/eval/runs', capability: 'evaluation', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/eval/runs', capability: 'evaluation', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/eval/runs/{run_id}', capability: 'evaluation', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/eval/runs/{run_id}/certify', capability: 'evaluation', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/extract-source', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/governance-dashboard', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/health-check', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/ingest-source', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/ingest-source/apply', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/ingest-source/batch', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/ingest-source/batch', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/ingest-source/batch/{job_id}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/ingest-source/batch/{job_id}/cancel', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/ingest-source/batch/{job_id}/resume', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/inhibitory-regulators', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/aging/scan', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/conflicts/scan', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/connections/scan', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/dashboard', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/duplicates/scan', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/findings', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/findings/{finding_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/findings/{finding_id}/dismiss', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/findings/{finding_id}/propose', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/findings/{finding_id}/resolve', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/findings/bulk-resolve', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/homeostasis/{scan_id}/apply', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/homeostasis/scan', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/reconciler/report', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/integrity/reconciler/sweep', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/runs', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/scans', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/integrity/scans/{scan_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/intra-department-bridge', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/labs/oracle-funnel', capability: 'evaluation', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/neuron-source-links', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'DELETE', path: '/admin/neuron-source-links/{link_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'PUT', path: '/admin/neuron-source-links/{link_id}/review', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/neurons/{neuron_id}/provenance', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/performance', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/performance/stage-telemetry', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/proposals/', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/proposals/{proposal_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/proposals/{proposal_id}/apply', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/proposals/{proposal_id}/review', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/proposals/dedup-clusters', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/proposals/stats', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/proposals/whoami', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/provenance/authority-summary', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/provenance/auto-link', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/provenance/recompute-authority', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/provenance/seed-sources', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/provenance/stale', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/prune-edges', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/purge-bootstrap', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/reference/documents', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/reference/documents', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/reference/documents/{canonical_id}', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/reference/documents/{canonical_id}/revoke', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/regions', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/admin/regions/{region}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'PUT', path: '/admin/regions/{region}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/admin/reset', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/retention/purge', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/scan-references', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/scoring-health', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seed', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seed-inhibitory-regulators', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seeding/cooccurrence-edges', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seeding/discover-regions', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seeding/knn-edges', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/seeding/retype-edges', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/source-documents', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/source-documents', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/source-documents/{doc_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'PUT', path: '/admin/source-documents/{doc_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/admin/source-documents/{doc_id}/supersede', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/system-banner', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/admin/tool-definitions', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/auditor/audit/{neuron_id}', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/auditor/candidates', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/auditor/run', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/auditor/status', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/capabilities/capsule', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/capabilities/health', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/capabilities/reconcile', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/capabilities/verify', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/chat', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/chat/sessions', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/chat/sessions', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'DELETE', path: '/chat/sessions/{session_id}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/chat/sessions/{session_id}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'PATCH', path: '/chat/sessions/{session_id}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/chat/sessions/{session_id}/generate-title', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/chat/sessions/{session_id}/messages', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/compile/run', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/compile/status', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/context', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/distill/run', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/distill/status', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/engrams/', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/engrams/{engram_id}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/engrams/{engram_id}/resolve', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/engrams/coverage/gaps', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/engrams/create', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/engrams/embed', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/engrams/seed', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/engrams/stats/summary', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/eval-scores', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/ingest/observation', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/ingest/observations', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/ingest/observations/{obs_id}', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/ingest/observations/{obs_id}/apply', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/ingest/observations/{obs_id}/approve', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/ingest/observations/{obs_id}/evaluate', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/ingest/observations/{obs_id}/reject', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/ingest/observations/evaluate-batch', capability: 'ingestion', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/janitor/as-of/{neuron_id}', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/janitor/corpus-health', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/janitor/history/{neuron_id}', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/janitor/run', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/janitor/status', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/learning-analytics', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/lineage/neuron/{neuron_id}/forward', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/lineage/neuron/{neuron_id}/overrides', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/lineage/neuron/{neuron_id}/overrides', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'DELETE', path: '/lineage/overrides/{override_id}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/lineage/query/{query_id}/trace', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/lineage/source/{source_id}/impact', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/delivery-pathways', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/inbox', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/injection-channels', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/jobs', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/locomo-run', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/sessions', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/skills', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/slo', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/subscription', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/subscription/codex', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/metrics/mind/trust', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/models', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/{neuron_id}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/{neuron_id}/edges', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/{neuron_id}/scores', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/capacity', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/children', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/clusters', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/edges/department-chord', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/edges/layer-flow', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/edges/spread-log', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/edges/spread-trail', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/graph-3d', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/refinements', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/stats', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/neurons/tree', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/queries', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/queries/{query_id}', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/queries/{query_id}/dossier', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/queries/run-counts', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/{query_id}/evaluate', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/{query_id}/followups', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/{query_id}/rate', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/{query_id}/refine', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/{query_id}/refine/apply', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/query/stream', capability: 'knowledge_graph', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/recall', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'POST', path: '/remember', capability: 'memory', tenants: ['corvus-locomo', 'corvus-mind'] },
  { method: 'GET', path: '/roadmap-ledgers', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/roadmap-ledgers', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/roadmap-ledgers/{slug}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'PATCH', path: '/roadmap-ledgers/{slug}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'PUT', path: '/roadmap-ledgers/{slug}', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/roadmap-ledgers/{slug}/admissions', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/roadmap-ledgers/{slug}/admissions', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/roadmap-ledgers/{slug}/nodes/{node_id}/reconcile', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/roadmap-ledgers/admission-context', capability: 'operator', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/v1/agents', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/v1/agents/{name}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/v1/agents/{name}/run', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/v1/agents/runs', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'GET', path: '/v1/agents/runs/{action_id}', capability: 'governance', tenants: ['corvus-mind'] },
  { method: 'POST', path: '/v1/query', capability: 'external_api', tenants: ['corvus-mind'] },
]

/** Routes mounted with no capability-owning router tag. Unowned, not hidden. */
export const UNOWNED_ROUTES: readonly string[] = [
  'GET /health',
  'GET /ready',
  'GET /tenant',
  'GET /tenants',
]

/** Capability that owns each route, keyed `METHOD /path`. */
export const ROUTE_CAPABILITY: Readonly<Record<string, Capability>> = Object.freeze(
  Object.fromEntries(ROUTE_CONTRACTS.map((r) => [`${r.method} ${r.path}`, r.capability])),
)

/** Capabilities each tenant profile grants, derived from what it actually mounts. */
export const TENANT_CAPABILITIES: Readonly<Record<TenantId, readonly Capability[]>> = Object.freeze({
  'corvus-locomo': ['knowledge_graph', 'memory'],
  'corvus-mind': ['evaluation', 'external_api', 'governance', 'ingestion', 'knowledge_graph', 'memory', 'operator'],
})

/**
 * True when the route is documented by SOME tenant but not granted by this one.
 *
 * A caller that gets `true` here should not render a network error: the
 * surface was composed away on purpose, and the page should not have been
 * reachable in the first place. A caller that gets `false` and still failed
 * has a real failure worth surfacing.
 */
export function isComposedAway(method: string, path: string, tenant: TenantId): boolean {
  const contract = ROUTE_CONTRACTS.find((r) => r.method === method && r.path === path)
  return contract ? !contract.tenants.includes(tenant) : false
}
