"""initial schema baseline

Revision ID: ae144af9c1e1
Revises: 
Create Date: 2026-03-21 15:45:49.405373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae144af9c1e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline reconciliation against the pre-alembic dev database.

    This migration was auto-generated against a dev DB that predated
    alembic — it only DROPS drift (leftover watcher tables, stale
    indexes) and tightens two columns; it does NOT create the core
    schema. Every object here may legitimately be absent (fresh DB, or
    a tenant that never ran the watcher), so every statement tolerates
    absence. Fresh-database bootstrap is Base.metadata.create_all +
    `alembic stamp head`, not `upgrade head` from zero.
    """
    for index in (
        "ix_corvus_work_streams_active",
        "ix_corvus_graph_edges_source",
        "ix_corvus_graph_edges_target",
        "uq_corvus_graph_edges_src_tgt_rel",
        "ix_corvus_graph_nodes_type",
        "ix_corvus_graph_nodes_value",
        "uq_corvus_graph_nodes_type_value",
        "ix_neuron_edges_source_weight",
        "ix_neuron_edges_target_weight",
    ):
        op.execute(f'DROP INDEX IF EXISTS "{index}"')
    for table in ("corvus_work_streams", "corvus_graph_edges", "corvus_graph_nodes"):
        op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
    op.execute(
        "ALTER TABLE IF EXISTS corvus_interpretations DROP COLUMN IF EXISTS embedding"
    )
    for column in ("eval_input_tokens", "eval_output_tokens"):
        op.execute(
            f"ALTER TABLE IF EXISTS observation_queue ALTER COLUMN {column} SET NOT NULL"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observation_queue', 'eval_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('observation_queue', 'eval_input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_neuron_edges_target_weight'), 'neuron_edges', ['target_id', 'weight'], unique=False)
    op.create_index(op.f('ix_neuron_edges_source_weight'), 'neuron_edges', ['source_id', 'weight'], unique=False)
    op.add_column('corvus_interpretations', sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('corvus_graph_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mention_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('corvus_graph_nodes_pkey'))
    )
    op.create_index(op.f('uq_corvus_graph_nodes_type_value'), 'corvus_graph_nodes', ['node_type', 'value'], unique=True)
    op.create_index(op.f('ix_corvus_graph_nodes_value'), 'corvus_graph_nodes', ['value'], unique=False)
    op.create_index(op.f('ix_corvus_graph_nodes_type'), 'corvus_graph_nodes', ['node_type'], unique=False)
    op.create_table('corvus_graph_edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['corvus_graph_nodes.id'], name=op.f('corvus_graph_edges_source_id_fkey')),
    sa.ForeignKeyConstraint(['target_id'], ['corvus_graph_nodes.id'], name=op.f('corvus_graph_edges_target_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('corvus_graph_edges_pkey'))
    )
    op.create_index(op.f('uq_corvus_graph_edges_src_tgt_rel'), 'corvus_graph_edges', ['source_id', 'target_id', 'relation_type'], unique=True)
    op.create_index(op.f('ix_corvus_graph_edges_target'), 'corvus_graph_edges', ['target_id'], unique=False)
    op.create_index(op.f('ix_corvus_graph_edges_source'), 'corvus_graph_edges', ['source_id'], unique=False)
    op.create_table('corvus_work_streams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('auto_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('entity_ids', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('interpretation_ids', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('corvus_work_streams_pkey'))
    )
    op.create_index(op.f('ix_corvus_work_streams_active'), 'corvus_work_streams', ['is_active'], unique=False)
    # ### end Alembic commands ###
